---
services:
  blog-system_database:
    image: postgres:latest
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blog_system
      POSTGRES_PASSWORD: blogsystempostgres123
      POSTGRES_DB: blog_system
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: blog-system_db
  
  blog-system_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: blog-system_app
    restart: no
    ports:
      - 3000:3000
    depends_on:
      - blog-system_database
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
    driver: local
...