---
services:
  blog-system_database:
    image: postgres:latest
    restart: no
    ports:
      - 5432:5432
    env_file:
      - .docker.env
    volumes:
      - pgdata:/data/postgres
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pgcrypto"
    container_name: blog-system_db

  blog-system_dbadmin:
    image: adminer:latest
    depends_on:
      - blog-system_database
    restart: no
    ports:
      - 8080:8080
    container_name: blog-system_dbadmin
  
  blog-system_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: blog-system_app
    restart: no
    ports:
      - 3000:3000
    depends_on:
      - blog-system_database
    volumes:
      - ./src:/app/src

volumes:
  pgdata:
    driver: local
...